# 1. Aşama: Build
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .

RUN mvn -f commerce/pom.xml clean package -DskipTests

# 2. Aşama: Run
FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

COPY --from=build /app/commerce/target/commerce-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]